# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4df199a5498325b04db22e860264761d66740c4c4edd304175db56f135104663e68bc0a76999f28c1e5d1a0d6c5e8ee4da50993d75cf70fed24092614d62fb1d

test:
  secret_key_base: f44ff06b775f3efe64de14593f2c5724e3a56f155ecf899dc652c406fa807dc39d1a9b5c80657e6cf7b8c9befafdca469aaebd740b4128b346a012be0138df7d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
